section .data
V1R DQ 0
V1C DQ 0
V2R DQ 0
V2C DQ 0

ROW_ITERATION DQ 0
CURRENT_ROW_INDEX DQ 0
STARTING_ROW_INDEX DQ 0

COLUMN_ITERATION DQ 0
CURRENT_COLUMN_INDEX DQ 0
STARTING_COLUMN_INDEX DQ 0

SUB1 DQ 0
SUB2 DQ 0
HOLDER DQ 0

section .text
bits 64
default rel
global matrixMul

matrixMul:
	PUSH RSI
	PUSH RBP
	MOV RBP, RSP
	ADD RBP, 16
	
	; PARAMETER STORE
	MOV RAX, [RBP + 40]
	MOV QWORD[V1C], RAX
	
	MOV RAX, [RBP + 48]
	MOV QWORD[V2R], RAX
	
	MOV RAX, QWORD[V1C]
	CMP RAX, QWORD[V2R]
	JNE DO_NOT_COMPUTE
	
	MOV RAX, [RBP + 56]
	MOV QWORD[V2C], RAX
	
	MOV QWORD[V1R], R9
	
	MOV R10, 0
	W1:
		; COPY R10 TO RAX
		MOV QWORD[ROW_ITERATION], R10
		MOV RAX, QWORD[ROW_ITERATION]
		MOV R10, QWORD[ROW_ITERATION]
		
		; COMPUTE FOR STARTING ROW INDEX
		IMUL RAX, QWORD[V1C]
		MOV QWORD[STARTING_ROW_INDEX], RAX
		
		MOV R11, 0
		W2:
			MOV QWORD[COLUMN_ITERATION], R11
			MOV R11, QWORD[COLUMN_ITERATION]
			
			; STARTING COLUMN INDEX IS EQUAL TO COLUMN ITERATION
			MOV QWORD[STARTING_COLUMN_INDEX], R11
			MOV R11, QWORD[STARTING_COLUMN_INDEX]
			
			; COMPUTATION LOOP
			MOV R12, QWORD[STARTING_ROW_INDEX]
			MOV R13, QWORD[STARTING_COLUMN_INDEX]
			MOV R14, 0
			MOV R15, 0
			W3:
				MOV QWORD[CURRENT_ROW_INDEX], R12
				MOV R12, QWORD[CURRENT_ROW_INDEX]
				MOV QWORD[CURRENT_COLUMN_INDEX], R13
				MOV R13, QWORD[CURRENT_COLUMN_INDEX]
				
				IMUL RAX, R12, 4
				MOV QWORD[SUB1], RAX
				ADD RCX, QWORD[SUB1]
				MOV RBX, [RCX]
				SUB RCX, QWORD[SUB1]
				
				MOV QWORD[HOLDER], RBX
				
				IMUL RAX, R13, 4
				MOV QWORD[SUB2], RAX
				ADD RDX, QWORD[SUB2]
				MOV RBX, [RDX]
				SUB RDX, QWORD[SUB2]
				
				IMUL RBX, QWORD[HOLDER]
				
				ADD R14, RBX
				
				MOV R12, QWORD[CURRENT_ROW_INDEX]
				INC R12
				MOV R13, QWORD[CURRENT_COLUMN_INDEX]
				ADD R13, QWORD[V2C]
				INC R15
				CMP R15, QWORD[V2R]
				JGE EW3
			JMP W3
			EW3:
			
			MOV [R8], R14D
			ADD R8, 4
			
			INC R11
			CMP R11, QWORD[V2C]
			JGE EW2
		JMP W2
		EW2:
		
		INC R10
		CMP R10, QWORD[V1R]
		JGE EW1
	JMP W1
	EW1:
	
	MOV RAX, 1
	JMP EN
	DO_NOT_COMPUTE:
	MOV RAX, 0
	EN:
	POP RBP
	POP RSI
	RET